# Generated by Django 3.0.4 on 2021-03-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbpessoa',
            options={'managed': True, 'ordering': ('no_pessoa', 'nu_cpf')},
        ),
    ]
